<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>36efb28c-9507-4ade-95d7-264f490e7d8c</UserSecretsId>
  </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Dapper" Version="2.1.79" />
        <PackageReference Include="MySqlConnector" Version="2.4.0" />
        <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    </ItemGroup>

</Project>
